sipnet_writer_traits_v2 <- c(
  "leafC",
  "SLA",
  "Amax",
  "AmaxFrac",
  "extinction_coefficient",
  "leaf_respiration_rate_m2",
  "Vm_low_temp",
  "psnTOpt",
  "growth_resp_factor",
  "half_saturation_PAR",
  "dVPDSlope",
  "dVpdExp",
  "leaf_turnover_rate",
  "wueConst",
  
  "veg_respiration_Q10",
  "stem_respiration_rate",
  "root_turnover_rate",
  "fine_root_respiration_Q10",
  "root_respiration_rate",
  "coarse_root_respiration_Q10",
  "root_allocation_fraction",
  "wood_allocation_fraction",
  "leaf_allocation_fraction",
  "wood_turnover_rate",
  
  "soil_respiration_Q10",
  "som_respiration_rate",
  "turn_over_time",
  "fracLitterRespired",
  "frozenSoilEff",
  "frozenSoilFolREff",
  "soilWHC",
  "immedEvapFrac",
  "leafWHC",
  "waterRemoveFrac",
  "fastFlowFrac",
  "rdConst",
  "water_drain_frac",
  
  "GDD",
  "leafOnReallocFrac",
  "fracLeafFall",
  "leafGrowth",
  
  "c2n_leaf",
  "c2n_wood",
  "c2n_fineroot",
  "kCN",
  "n_volatilization_rate",
  "n_leaching_frac",
  "n_fixation_frac_max",
  "n_fix_half_sat",
  "f_anoxia",
  "anaerobic_decomp_rate",
  "anaerobic_trans_exp",
  "soil_methane_rate",
  "litter_methane_rate"
)

all_try_traits <- c(
  "Bark thickness",
  "Coarse root to fine root mass ratio",
  "Coarse woody debris (CWD) stem: carbon (C) content per stem CWD",
  "Coarse woody debris (CWD) stem: carbon/nitrogen (C/N) ratio",
  "Coarse woody debris (CWD) stem: decomposition rate",
  "Coarse woody debris (CWD) stem: decomposition rate constant",
  "Coarse woody debris (CWD) stem: nitrogen (N) content per stem CWD",
  "Fine root carbon (C) content per fine root dry mass",
  "Fine root carbon/nitrogen (C/N) ratio",
  "Fine root diameter",
  "Fine root dry mass per fine root fresh mass (fine root dry matter content; RDMC)",
  "Fine root dry mass to leaf dry mass ratio",
  "Fine root dry mass turnover rate",
  "Fine root length per fine root dry mass (specific fine root length, SRL)",
  "Fine root nitrogen (N) content per fine root dry mass",
  "Fine root phosphorus (P) content per fine root dry mass",
  "Fine root respiration rate per fine root dry mass",
  "Fine root rooting depth",
  "Fine root tissue density (fine root dry mass per fine root volume)",
  "Fine root/shoot ratio",
  "Leaf area per leaf dry mass (specific leaf area, SLA or 1/LMA): petiole excluded",
  "Leaf area per leaf dry mass (specific leaf area, SLA or 1/LMA): petiole included",
  "Leaf area per leaf dry mass (specific leaf area, SLA or 1/LMA): undefined if petiole is in- or excluded",
  "Leaf carbon (C) content per leaf area",
  "Leaf carbon (C) content per leaf dry mass",
  "Leaf carbon/nitrogen (C/N) ratio",
  "Leaf cellulose content per leaf dry mass",
  "Leaf construction cost per leaf area",
  "Leaf construction cost per leaf dry mass",
  "Leaf density (leaf tissue density, leaf dry mass per leaf volume)",
  "Leaf dry mass per leaf fresh mass (leaf dry matter content, LDMC)",
  "Leaf hemi-cellulose content per leaf dry mass",
  "Leaf hydraulic conductance",
  "Leaf lifespan (longevity)",
  "Leaf lignin content per leaf dry mass",
  "Leaf mesophyll conductance",
  "Leaf nitrogen (N) content per leaf area",
  "Leaf nitrogen (N) content per leaf dry mass",
  "Leaf nitrogen/phosphorus (N/P) ratio",
  "Leaf phenology type",
  "Leaf phosphorus (P) content per leaf area",
  "Leaf phosphorus (P) content per leaf dry mass",
  "Leaf respiration rate in the dark as fraction of photosynthetic carboxylation capacity (Vcmax)",
  "Leaf respiration rate in the dark per leaf area",
  "Leaf respiration rate in the dark per leaf dry mass",
  "Leaf respiration rate in the dark temperature dependence",
  "Leaf thickness",
  "Leaf transpiration rate per leaf area",
  "Leaf type",
  "Leaf water & osmotic potential: leaf osmotic potential at full turgor",
  "Leaf water & osmotic potential: leaf osmotic potential at turgor loss",
  "Leaf water & osmotic potential: leaf water potential at turgor loss point",
  "Leaf water potential midday",
  "Leaf water potential predawn",
  "Leaf water storage capacity (WSC)",
  "Litter carbon (C) content per litter dry mass",
  "Litter carbon/nitrogen (C/N) ratio",
  "Litter cellulose content per litter dry mass",
  "Litter decomposition rate",
  "Litter decomposition rate constant",
  "Litter lignin content per litter dry mass",
  "Litter nitrogen (N) content per litter dry mass",
  "Litter phosphorus (P) content per litter dry mass",
  "Litter SLA (leaf area per leaf dry mass, specific leaf area, 1/LMA of leaf litter)",
  "Litter tannin content per litter dry mass",
  "Mycorrhiza type",
  "Photosynthesis carboxylation capacity (Vcmax) per leaf area (Farquhar model)",
  "Photosynthesis carboxylation capacity (Vcmax) per leaf dry mass (Farquhar model)",
  "Photosynthesis electron transport capacity (Jmax) per leaf area (Farquhar model)",
  "Photosynthesis electron transport capacity (Jmax) per leaf dry mass (Farquhar model)",
  "Photosynthesis light use efficiency (LUE)",
  "Photosynthesis pathway",
  "Photosynthesis quantum yield (QY; corresponding to photosynthetic efficiency)",
  "Photosynthesis rate per leaf area",
  "Photosynthesis rate per leaf dry mass",
  "Photosynthesis rate per leaf nitrogen (N) content (photosynthetic nitrogen use efficiency, PNUE)",
  "Photosynthesis rate per leaf transpiration (photosynthetic water use effinciency: WUE)",
  "Photosynthesis: intercellular CO2 concentration",
  "Photosynthesis: intercellular CO2 concentration to ambient CO2 (ci/ca)",
  "Plant biomass and allometry: Root mass fraction (fraction of root dry mass per whole plant dry mass)",
  "Plant biomass and allometry: Stem dry mass per plant",
  "Plant biomass and allometry: Stem dry mass per plant dry mass",
  "Plant functional type (PFT)",
  "Plant growth form",
  "Plant growth form simple consolidated",
  "Plant height",
  "Plant height vegetative",
  "Plant life form (Raunkiaer life form)",
  "Plant nitrogen(N) fixation capacity",
  "Plant vegetative phenology (leaf phenology)",
  "Plant woodiness",
  "Root carbon (C) content per root dry mass",
  "Root carbon/nitrogen (C/N) ratio",
  "Root diameter",
  "Root dry mass per root fresh mass (root dry matter content; RDMC)",
  "Root dry mass turnover rate",
  "Root length per root dry mass (specific root length, SRL)",
  "Root nitrogen (N) content per root dry mass",
  "Root phosphorus (P) content per root dry mass",
  "Root respiration rate per root dry mass",
  "Root rooting depth",
  "Root tissue density (root dry mass per root volume)",
  "Root/shoot ratio",
  "Species tolerance to drought",
  "Species tolerance to frost",
  "Species tolerance to shade",
  "Species tolerance to waterlogging",
  "Stem carbon (C) content per stem dry mass",
  "Stem carbon/nitrogen (C/N) ratio",
  "Stem diameter",
  "Stem dry mass per stem fresh mass (stem dry matter content, StDMC)",
  "Stem hydraulic conductivity",
  "Stem length",
  "Stem nitrogen (N) content per stem dry mass",
  "Stem specific density (SSD, stem dry mass per stem fresh volume) or wood density",
  "Stem specific density (SSD, stem dry mass per stem fresh volume) or wood density: branch",
  "Stem specific density (SSD, stem dry mass per stem fresh volume) or wood density: sapwood",
  "Wood (sapwood) specific conductivity (stem specific conductivity)",
  "Wood dry mass per saturated wood fresh mass (wood dry matter content, WDMC)",
  "Wood nitrogen (N) content per wood dry mass"
)
